### ISSUE TITLE
3_kun_keyboard_catcher目录下缺少 requirements.txt 

### ISSUE THREAD

**Issue by For-December** [ShenYuhan/python-tools#3]

**Comment by Sho-Shoo** [comment]
复议

**Comment by For-December** [comment]
> 

pip install pynput
pip install PyQt5
pip install pyinstaller
安装这三个依赖项即可

**Comment by For-December** [comment]
> 复议

pip install pynput
pip install PyQt5
pip install pyinstaller
安装这三个依赖项即可

**Comment by ShenYuhan** [comment]
requirments.txt已经添加，问题关闭
